### PR TITLE
feat(media): Add media helper method to create image descriptions

### PR DESCRIPTION
**Pull request by klausi**
Problem: we want to provide alt text descriptions for images because of accessibility.

The Mastodon API supports that via the description parameter, see https://docs.joinmastodon.org/api/rest/media/

I did not want to introduce an API break for the existing media() method, so I created media_description(). What do you think?

### CODE REVIEW

**Comment by Aaronepower** [comment]
@klausi Thank you for your PR! I'd prefer a breaking change also with the focal points. Is there a reason this is done by hand and not through the `route!` macro? It seems like it could handle it.

**Comment by klausi** [comment]
I think the route macro will not help us because the form multipart code can only be used for this media api call. So I would write this in non macro code to be less confusing and easier to read.

**Comment by klausi** [comment]
Added support for focus point as `(f32, f32` tuple. Introduced the media method API break, moved from the macro to the simpler direct Rust version.

Ready for review again!

**Comment by Aaronepower** [comment]
@klausi Thank you for working on this, overall this looks good to me. I would change the arguments., as I dislike multiple `Option` arguments, I find that it makes more annoying to call a method. I would add a `MediaBuilder` struct that follows the builder pattern for the struct. It'd also be nice to have a `impl From<MediaBuilder> for Form` so that the conversion logic is not in the actual route method itself. I would also add  a `impl From<Cow<'static, str>> for MediaBuilder` and have the argument be `builder: Into<MediaBuilder>` so that practically this shouldn't break anyone's existing code, and makes the maybe most common way to call this function is easy.


The ideal call would be something like this.

## Just File
```rust
let attachment = mastodon.media(Cow::Borrowed("./image.png"));
```

## With alt text
```rust
let attachment = mastodon.media(MediaBuilder::new("./image.png").description("A picture of a nice dog"));
```

## With all arguments
```rust
let attachment = mastodon.media(
    MediaBuilder::new("./image.png")
        .description("A picture of a nice dog")
        .focus(200, 200)
);
```

**Comment by klausi** [comment]
OK, refactored to use a media builder.

This fails to compile now in the example code:
```
error[E0277]: the trait bound `register::mammut::MediaBuilder: std::convert::From<std::string::String>` is not satisfied
 --> examples/upload_photo.rs:9:26
  |
9 |     mastodon.media(input.into())?;
  |                          ^^^^ the trait `std::convert::From<std::string::String>` is not implemented for `register::mammut::MediaBuilder`
  |
  = help: the following implementations were found:
            <register::mammut::MediaBuilder as std::convert::From<std::borrow::Cow<'static, str>>>
  = note: required because of the requirements on the impl of `std::convert::Into<register::mammut::MediaBuilder>` for `std::string::String`
```

I only implemented a From for `Cow<'static, str>`, can I tell Rust to transitively convert String to Cow<'static, str> to MediaBuilder?

I also tried to use your suggestion with `Into<MediaBuilder>`, but that does not work either:
```
error[E0038]: the trait `std::convert::Into` cannot be made into an object
   --> src/lib.rs:693:5
    |
693 | /     pub fn media(&self, media_builder: Into<MediaBuilder>)
694 | |         -> Result<Attachment>
695 | |     {
696 | |         use reqwest::multipart::Form;
...   |
723 | |         deserialise(response)
724 | |     }
    | |_____^ the trait `std::convert::Into` cannot be made into an object
    |
    = note: the trait cannot require that `Self : Sized`
```

How do you use `Into` as parameter correctly in Rust? What does `Sized` mean here? Maybe that `struct Mastodon` is not Sized, but it should be? How could we make it Sized?

Any hints how to make this work?

**Comment by Aaronepower** [comment]
@klausi I would just add a `From<String> for MediaBuilder` that just calls the `From<Cow<'static, str>> for MediaBuilder` with `Cow::Owned(string)`

**Comment by klausi** [comment]
Ok, implemented converters for 3 Rust string types: String, &str and Cow<'static &str>. It compiles now, yay! Any other String types that people use? 

BTW: I did not implement your `impl From<MediaBuilder> for Form` suggestion because that would just add another layer of indirection for this simple code. I would contain the form conversion logic in the media() method since it is quite short and this is not used elsewhere. Anyway, I could also change that if you really want!

**Comment by Aaronepower** [comment]
@klausi Thank you for your work! I'm fine with that not being implemented right now, though I do think more and more methods will become like this as the API grows, but that is in the future.

**Comment by klausi** [comment]
Cool, thank you!

**Comment by klausi** [comment]
Sorry, this broke image uploads in interesting ways, opened #48

**Pull request merged**
