### PR TITLE
fix(errors): Directly pass up Serde errors for easier debugging

### PR DESCRIPTION
**Pull request by klausi**
When I was debugging the account ID problem from #15 I got this obscure error:

```
Err(Serde(ErrorImpl { code: Message("missing field `error`"), line: 1, column: 894 }))
```
But there is no error field on the account? How could library think that there is an error field?

With this pull request the error is

```
Err(Serde(ErrorImpl { code: Message("invalid type: string \"28407\", expected u64"), line: 1, column: 13 }))
```
Still quite bad because it does neither mention the type it tries to serialize nor which field is broken, but better than before.

### CODE REVIEW

**Comment by Aaronepower** [comment]
@klausi Thank you for the issues and PRs! I actually wrote a similar implementation while I was fixing up 0.9. The problem though is that sometimes the API does give a legitimate error. So we can't remove serialising to `ApiError`. I think the best compromise is something like the following where if we can't serialise to an error we give them the error of the original. I don't think it's too important to be super clear since these type of errors should be rare.

```rust
if let Ok(t) = json::from_slice(&vec) {
    Ok(t)
} else if let Ok(t) = json::from_slice(&vec) {
    Err(Error::Api(t))
} else {
   // Guaranteed to fail
   Ok(json::from_slice(&vec)?)
}
```

**Comment by klausi** [comment]
I see, but then the third json::from_slice() is not needed, then we can just return the error from the first try.

**Comment by klausi** [comment]
I implemented a test case for this, but I'm not happy with all the boiler plate mocking I need to do. Any better ideas how to test this?

**Comment by klausi** [comment]
Merged in #17 to see tests pass and fixed error message assertion after reordering of fields

**Comment by Aaronepower** [comment]
@klausi I'm not so sure mocking is the correct thing to do since we're only testing our own sources this doesn't let us know if it actually works with the API. Also the error code should probably be a function so it can be reused as currently there are functions that don't call the functions generated by the method! macro.

**Comment by klausi** [comment]
Good idea with the shared JSON converting function! Implemented that.

I also threw the test case away again since now even the slightest changes in the function breaks it. Does not seem useful in that form. No good idea how we should do testing otherwise.

**Pull request merged**
