### PR TITLE
Fixed the registration of new apps as well as url of statuses is now an Option<String>

### PR DESCRIPTION
**Pull request by TheBestJohn**
includeing jhaye's String fixes. Here are some other errors I was running into that were popping up on the new API

### CODE REVIEW

**Comment by TheBestJohn** [comment]
This requires a change of tests to use Scopes instead of Scope

**Comment by TheBestJohn** [comment]
I'm a fool. Learning about cargo test now...

**Comment by jhaye** [comment]
You should probably clean up your commit log. Currently you have seven commits, whereof one is mine and the rest are yours.

I propose that you squash your six commits like this:
`git reset --soft HEAD~6` to undo your six commits and
`git commit` to commit all changes at once and finally
`git push -f` to push to your branch (the -f is to overwrite your git commit history).

**Comment by Aaronepower** [comment]
@TheBestJohn Thank you for this PR!

@jhaye The commit amount doesn't matter on pull requests as the commits will be squashed before I merge them regardless.

**Comment by jhaye** [comment]
@Aaronepower alright, I assumed you would simply merge. My mistake.

**Comment by TheBestJohn** [comment]
@jhaye Thank you for the advice :) This is going to be the first repo I've really committed to officially and the etiquette is still new to me. I'll keep this in mind in the future. 

@Aaronepower No problem! Thank you for posting it in the first place 👍

**Comment by Aaronepower** [comment]
@thebestjohn The etiquette will vary between repos and how they prefer to merge. Some repos specify their style in the `CONTRIBUTING.md` For example: [hyper’s](https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md). For any repo I own I always squash and merge so you don’t need to rebase on those PRs.

**Comment by TheBestJohn** [comment]
I've been looking into the API some more on another topic but my attention was drawn to the `route!` macros. Some of them are still looking for u64 ids and may need to be changed. I don't know enough about macros yet to do anything with them but if anyone knows more please take a look.

**Comment by Aaronepower** [comment]
@TheBestJohn Thank you for this PR and congrats on your first contribution!

**Pull request merged**
