### PR TITLE
Fix registration for Pleroma instances

### PR DESCRIPTION
**Pull request by BrainBlasted**
When making the API call to register, Mastodon would return the
`redirect_uri` field while Pleroma wouldn't. Since the API documentation suggests using `urn:ietf:wg:oauth:2.0:oob` as
a default of sorts, we can use this to handle the difference between instances.

`redirect_uri` is now an Option field, so Serde will not be upset if it is missing, and then if missing the default will be used.

Related: #32

### CODE REVIEW

**Comment by Aaronepower** [comment]
Thank you for your PR! I don't think it should default to the OAuth equivalvent of null as that could lead to unexpected behaviour. It should simply not provide the `redirect_uri` parameter if it is none.

**Comment by BrainBlasted** [comment]
@Aaronepower, authorization fails if you omit that parameter completely, so the fallback is correct.

**Comment by Aaronepower** [comment]
@BrainBlasted If Plemora doesn't work without this parameter then why would it be optional?

**Comment by BrainBlasted** [comment]
@Aaronepower , according to https://github.com/tootsuite/documentation/blob/master/Using-the-API/OAuth-details.md it isn't optional.

**Comment by Aaronepower** [comment]
Then I'm going to close this issue as a bug Plemora's code than Mammut's.

**Pull request closed without merging**
