### PR TITLE
[WIP] Klausi's Mammut fork

### PR DESCRIPTION
**Pull request by klausi**
I had to fix quite a few things to get Mammut working for my use case, here is my fork for comparison. I'm using that in my project with Cargo.toml:

```toml
[dependencies]
mammut = ">=0.9"

[patch.crates-io]
mammut = { git = "https://github.com/klausi/Mammut", branch = "klausi" }
```

This is not at all merge-ready, but could be useful for other people. Feel free to merge back bits and pieces as you see fit!

### CODE REVIEW

**Comment by Aaronepower** [comment]
@klausi Thanks for this PR! Some the work here is out of sync with your other PRs, can those PRs be updated with the code present in this fork?

**Comment by klausi** [comment]
Done, updated the other PRs.

**Comment by klausi** [comment]
So it seems like you are going now with a String only type in #20 , so this is obsolete.

**Comment by klausi** [comment]
Ah, closed the wrong PR, sorry.

**Comment by klausi** [comment]
So the 2 remaining features I have in my fork:
* Optionally limiting statuses by max_id and since_id. I could move this to its own function to avoid API breaks with the new parameters. Just need a good name. `fn statuses_limited()`? `fn statuses_since_max`?
* Fetching favourites.

**Comment by Aaronepower** [comment]
@klausi I'm going to close this as inspired by this fork I've tried to implement a general solution to pagination, can you try and use it see if it suits your needs with favourites and then if it does I can add the rest of the pagination routes.

**Comment by klausi** [comment]
Thanks @Aaronepower! I tested the favourites pagination and it works. The only minor annoying thing is the code duplication I have to do. First I have to deal with initial_items, then I have to iterate through the next pager:

```rust
fn mastodon_fetch_fav_dates(mastodon: &Mastodon, cache_file: &str) -> BTreeMap<DateTime<Utc>, u64> {
    let mut dates = BTreeMap::new();
    let mut favourites_pager = mastodon.favourites().unwrap();
    for status in &favourites_pager.initial_items {
        let id = u64::from_str(&status.id).unwrap();
        dates.insert(status.created_at, id);
    }
    loop {
        let statuses = favourites_pager.next_page().unwrap();
        if statuses.is_none() {
            break;
        }
        for status in statuses.unwrap() {
            let id = u64::from_str(&status.id).unwrap();
            dates.insert(status.created_at, id);
        }
    }

    save_dates_to_cache(cache_file, &dates);

    dates
}
```

**Comment by Aaronepower** [comment]
@klausi I would say you could reduce the code duplication by doing what I've shown below. I think having the initial items seperate is important as getting everything is a very small use case,  a lot of times you either want to get the initial bunch, or get them on demand when the user actually requests to see that data, there could maybe the argument for a `favourites_complete` function, but it'd need to come with a lot of caveats as you could easily exceed your API threshold calling that.

```rust
fn mastodon_fetch_fav_dates(mastodon: &Mastodon, cache_file: &str)
    -> BTreeMap<DateTime<Utc>, u64>
{
    let mut favourites_pager = mastodon.favourites().unwrap();
    let mut items: BTreeMap<_, _> = favourites_pager.initial_items
        .iter()
        .filter_map(map_to_dates)
        .collect();

    loop {
        let statuses = match favourites_pager.next_page() {
            Ok(Some(statuses)) => statuses,
            _ => break,
        };

        for (k, v) in statuses.iter().filter_map(map_to_dates) {
            items.insert(k, v);
        }
    }

    items
}

fn map_to_dates(status: &Status) -> Option<(DateTime<Utc>, u64)> {
    Some((status.created_at, u64::from_str(&status.id).ok()?))
}
```

**Comment by Aaronepower** [comment]
@klausi I've now published `0.10.0-rc2` which moves all previous `Vec` routes to `Page` could you try it out before I make a release `0.10.0`.

**Comment by klausi** [comment]
Nice! Everything seems to work as expected on my end. I was able to remove my Mammut fork as dependency now for https://github.com/klausi/mastodon-twitter-sync , yay!

You have some serious macro writing skills, congrats!

**Pull request closed without merging**
